<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>BatteryEms.Adapters.Entsoe</RootNamespace>
    <AssemblyName>BatteryEms.Adapters.Entsoe</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\hexagon\BatteryEms.Application\BatteryEms.Application.csproj" />
  </ItemGroup>

</Project>
