<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>BatteryEms.BrokerRecovery.TestHost</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/host/BatteryEms.BrokerHost/BatteryEms.BrokerHost.csproj" />
  </ItemGroup>
</Project>
